//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTENDANCE
    {
        public decimal MEMBER_NO { get; set; }
        public Nullable<System.DateTime> ATTENDANCE_DATE { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> ATT_TIME { get; set; }
    }
}
