//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKING
    {
        public decimal BOOKING_ID { get; set; }
        public Nullable<decimal> MEM_NO { get; set; }
        public string F_NAME { get; set; }
        public Nullable<System.DateTime> BOOK_DATE { get; set; }
        public string TIME_SLOT { get; set; }
    }
}
