//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBER
    {
        public decimal MEMBERSHIP_NO { get; set; }
        public string FULL_NAME { get; set; }
        public string GENDER { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<decimal> MOBILE_NO { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string EMER_CONT_PERS { get; set; }
        public Nullable<decimal> EMER_CONT_PERS_NO { get; set; }
        public string SYS_PASSWORD { get; set; }
    }
}
